#!/bin/sh
#
# Layer 2 Switch
#
#


case "$1" in
	start)
		#
		# Create a single untagged vlan (i.e. interface), consisting
		# of the 26 Gigabit Ethernet ports Layer 2 forwarding enabled
		# Put the ISL in its own vlan to avoid loops
		#
		/usr/sbin/zconfig zhp0: vlan1=zre0..25
		/usr/sbin/zconfig zre0..25=untag1

    zkeyd -e zre0
    zkeyd -e zre1
    zkeyd -e zre2
    zkeyd -e zre3
    zkeyd -e zre4
    zkeyd -e zre5
    
		ifconfig zhp0 192.168.1.22 netmask 255.255.255.0 broadcast 192.168.1.255 up

		;;
	stop)
		#
		# Bring down the interface
		#
		ifconfig zhp0 down
		/usr/sbin/zconfig zhp0:teardown
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac
